// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4pcDK2vLWg0BlwbMOi9KI5cVYPBcq_iI',
    appId: '1:393021429410:web:806ed1954b8a57587e69fb',
    messagingSenderId: '393021429410',
    projectId: 'dbase-b5cec',
    authDomain: 'dbase-b5cec.firebaseapp.com',
    storageBucket: 'dbase-b5cec.appspot.com',
    measurementId: 'G-XZT76DH6T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzgZ5U289F5hWXzzojgAb1oxet8N1Cgk',
    appId: '1:393021429410:android:f571611cf04a3e1e7e69fb',
    messagingSenderId: '393021429410',
    projectId: 'dbase-b5cec',
    storageBucket: 'dbase-b5cec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsywvxKwSzg6t3hBUZPfo0Hy3FRh-tOf8',
    appId: '1:393021429410:ios:4783f6f65837c2167e69fb',
    messagingSenderId: '393021429410',
    projectId: 'dbase-b5cec',
    storageBucket: 'dbase-b5cec.appspot.com',
    iosClientId: '393021429410-r7tb0i8032llpm105rkuhb60q4odi3rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsywvxKwSzg6t3hBUZPfo0Hy3FRh-tOf8',
    appId: '1:393021429410:ios:69ec794ba86e493c7e69fb',
    messagingSenderId: '393021429410',
    projectId: 'dbase-b5cec',
    storageBucket: 'dbase-b5cec.appspot.com',
    iosClientId: '393021429410-rb536jhs6hb11idr9p3micl0tnejg5ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProject.RunnerTests',
  );
}
